version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3001:3000
    depends_on:
      - db
    command: sh ./docker/docker_bash.sh
    tty: true
    stdin_open: true

volumes:
  mysql_data:
  bundle:
