default: &default
  adapter: mysql2
  encoding: utf8mb4
  host:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: anime_development

test:
  <<: *default
  database: anime_test

production:
  <<: *default
  database: anime_production
  username: anime
  password: <%= ENV['ANIME_DATABASE_PASSWORD'] %>
